---
version: '3'
name: AWS Kubernetes Cluster (EKS)
canonical: kubernetes-aws-eks
description: |
  Manage AWS EKS Control Plane and Node Groups
keywords:
  - Cycloid
  - kubernetes
  - k8s
  - eks
  - rds
  - redis
author: Cycloid
image: https://cycloid-demo-stacks-logo.s3.eu-west-1.amazonaws.com/kubernetes.png

config:
  default:
    name: AWS EKS
    description: Manage a EKS Control Plane, node group, iam, vpc, subnet ...
    pipeline:
      pipeline:
        path: pipeline/pipeline.yml
      variables:
        path: pipeline/variables-aws-eks.sample.yml
        destination: '($ .project $)/pipeline/($ .environment $)/variables.yml'
    terraform:
      eks:
        path: 'terraform/main.tf'
        destination: '($ .project $)/terraform/($ .environment $)/main.tf'
