---
version: "2"
use_cases:
- name: default
  sections:
  - name: Azure Function
    groups:
    - name: Function Code
      technologies: [pipeline]
      vars:
      - name: "Function Git Repository URL"
        description: "Public git URL of the function to deploy."
        key: git_func_url
        widget: auto_complete
        type: string
        values: ["https://github.com/mattchenderson/azure-functions-starter-javascript.git","https://github.com/cycloid-community-catalog/onboarding-functions.git"]
        default: "https://github.com/cycloid-community-catalog/onboarding-functions.git"
        required: true
      - name: "Function Git Repository Branch"
        description: "Git Repository Branch of the function to deploy."
        key: git_func_branch
        widget: auto_complete
        type: string
        values: ["master","main","develop"]
        default: "master"
        required: true
      - name: "Function Git Repository Package Path"
        description: "Git Repository Path of the function package (zip file) to deploy."
        key: git_func_package
        widget: auto_complete
        type: string
        values: ["azurevnets/azurevnets.zip"]
        default: ""
        required: false

    - name: Azure Access Configuration
      technologies: [pipeline]
      vars:
      - name: "Azure credentials"
        description: "The azure credential used to deploy the infrastructure. It contains subscription_id, tenant_id, client_id, and client_secret."
        key: azure_cred
        widget: cy_cred
        widget_config:
          display_keys: false
          cred_types:
            - azure
        type: string
        default: "((azure))"
        required: true
    - name: Azure Infrastructure
      technologies: [terraform]
      vars:
      - name: "Resource Group"
        description: "The name of the existing resource group where the resources will be deployed."
        key: resource_group_name
        widget: cy_inventory_resource
        widget_config:
          attribute: name
          filters:
            type: azurerm_resource_group
        type: string
        required: true
      - name: "Azure location"
        description: "Azure location for Terraform."
        key: azure_location
        widget: auto_complete
        type: string
        values_ref: https://cycloid-demo-stackforms-values.s3.eu-west-1.amazonaws.com/azure-locations.json
        default: "West Europe"
        required: true
