---
# Configuration of the Cycloid stack
version: '3'
name: 'Nexus Repository'
canonical: 'stack-nexus-repository'
description: 'Deploys a Nexus Repository on a Kubernetes cluster using a Helm chart.'
author: 'Cycloid'
image: 'https://cycloid-demo-stacks-logo.s3.eu-west-1.amazonaws.com/nexus.png'
status: 'private'
keywords:
- 'nexus'
- 'repository'
- 'artefact'
- 'provider:kubernetes'
technologies:
- technology: nexus
  version: "3.33"
- technology: terraform
  version: 1.8.3

config:
  kubernetes:
    name: 'Kubernetes'
    description: 'Deploys a Nexus Repository in a Kubernetes cluster'
    cloud_provider: kubernetes
    # Pipeline and variable configuration for the GCP CD pipeline use case
    pipeline:
      pipeline:
        path: 'pipeline/pipeline.yml'
      variables:
        path: 'pipeline/variables.sample.yml'
        destination: '($ .project $)/pipeline/($ .environment $)/variables.yml'
    # Configuration of terraform
    terraform:
      main:
        path: 'terraform/main.tf'
        destination: '($ .project $)/terraform/($ .environment $)/main.tf'