resource_types:
  - name: api-call
    type: docker-image
    source:
      repository: jgriff/http-resource

resources:
  # - name: github-org-repo
  #   type: api-call
  #   source:
  #     url: https://api.github.com/orgs/((github-org))/repos
  #     headers:
  #       Accept: application/vnd.github+json
  #       X-GitHub-Api-Version: 2022-11-28
  #       Authorization: Bearer ((github-token))
  #     version:
  #       jq: .id
  #       default: none

  - name: github-user-repo
    type: api-call
    source:
      url: https://api.github.com/user/repos
      headers:
        Accept: application/vnd.github+json
        X-GitHub-Api-Version: 2022-11-28
        Authorization: Bearer ((github-token))
      version:
        jq: .id
        default: none

groups:
- name: overview
  jobs:
    - get-github-repo

jobs:
  - name: get-github-repo
    plan:
      - get: github-user-repo
        trigger: true
      - task: take-a-look
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: busybox }
          inputs:
            - name: github-user-repo
          run:
            path: cat
            args: ["github-user-repo/headers", "github-user-repo/body"]



# {"name":"Hello-World","description":"This is your first repo!","homepage":"https://github.com","private":false,"is_template":true}

