resource_types:
  - name: http-api
    type: docker-image
    source:
      repository: aequitas/http-api-resource
      tag: latest

resources:
  # - name: github-org-repo
  #   type: http-api
  #   source:
  #     url: https://api.github.com/orgs/((github-org))/repos
  #     headers:
  #       Accept: application/vnd.github+json
  #       X-GitHub-Api-Version: 2022-11-28
  #       Authorization: Bearer ((github-token))
  #     version:
  #       jq: .id
  #       default: none

  - name: github-user-repo
    type: http-api
    source:
      uri: https://api.github.com/user/repos
      method: POST
      headers:
        Accept: application/vnd.github+json
        X-GitHub-Api-Version: '2022-11-28'
        Authorization: "Bearer {github-token}"
      github-token: ((github-token))
      json:
        name: "{repo_name}"
        description: "{repo_description}"
        homepage: "https://github.com"
        private: true
        is_template: false

groups:
- name: overview
  jobs:
    - get-github-repo

jobs:
  - name: get-github-repo
    plan:
      - put: github-user-repo
        params:
          repo_name: ((repo_name))
          repo_description: ((repo_description))
        
      - task: take-a-look
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: busybox }
          inputs:
            - name: github-user-repo
          run:
            path: cat
            args: ["github-user-repo/headers", "github-user-repo/body"]