---
# Configuration of the Cycloid stack
version: '2'
name: 'OWASP Zed Attack Proxy'
canonical: 'stack-owasp-zap'
description: "Deploys the world's most widely used web app scanner. Free and open source. Actively maintained by a dedicated international team of volunteers. A GitHub Top 1000 project."
author: 'Cycloid'
image: 'https://cycloid-demo-stacks-logo.s3.eu-west-1.amazonaws.com/owasp-zap.png'
status: 'public'
keywords:
- owasp
- zed
- attack
- proxy
- zap
- pentest
- provider:aws
technologies:
- technology: zap
  version: "2.14.0"

config:
  aws:
    name: 'AWS'
    description: 'Deploys OWASP Zed Attack Proxy (ZAP) in a single AWS instance'
    cloud_provider: aws
    # Pipeline and variable configuration for the AWS CD pipeline use case
    pipeline:
      pipeline:
        path: 'pipeline/pipeline.yml'
      variables:
        path: 'pipeline/variables.sample.yml'
        destination: '($ project $)/pipeline/($ environment $)/variables.yml'
    # Configuration of terraform (leave .sample extension to prevent terraform executing the sample file)
    terraform:
      main:
        path: 'terraform/main.tf'
        destination: '($ project $)/terraform/($ environment $)/main.tf'
