groups:
- name: overview
  jobs:
    - deploy

jobs:
  - name: deploy
    serial: true
    max_in_flight: 1
    build_logs_to_retain: 10
    plan:
      - in_parallel:
        - get: git_stack-terraform
          trigger: true
        - get: git_config-terraform
          trigger: true

  - name: run-operations
    serial: true
    max_in_flight: 1
    build_logs_to_retain: 10
    plan:

      - task: run-cli-operations
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: amazon/aws-cli
              tag: latest
          run:
            path: /bin/bash
            args:
              - '-c'
              - |
                yum install jq -y >/dev/null
                export instance_id=$(cat tfstate/metadata | jq -r .instance_id)
                export AWS_ACCESS_KEY_ID=$(echo ${CY_AWS_CRED} | jq -r .access_key)
                export AWS_SECRET_ACCESS_KEY=$(echo ${CY_AWS_CRED} | jq -r .secret_key)
                export AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
                export TERM=xterm
                if [[ "$vm_instance_status" = "Started" ]]; then
                  echo "Starting instance ${instance_id}..."
                  aws ec2 start-instances --instance-ids ${instance_id}
                elif [[ "$vm_instance_status" = "Stopped" ]]; then
                  echo "Stopping instance ${instance_id}..."
                  aws ec2 stop-instances --instance-ids ${instance_id}
                fi
          inputs:
          - name: tfstate
            path: tfstate
        params:
          vm_instance_status: '((vm_instance_status))'
          CY_AWS_CRED: '((aws_cred))'
          AWS_DEFAULT_REGION: '((aws_region))'
