---
version: "2"
use_cases:
- name: aws
  sections:
  - name: Nexus Repository
    groups:
    - name: Virtual machine specifications
      technologies: [terraform]
      vars:
      - name: "Instance type"
        description: "Instance type for the Nexus Repository."
        key: vm_instance_type
        widget: slider_list
        type: string
        default: "t3a.medium"
        values:
            - "t3a.medium"
            - "t3a.large"
            - "t3a.xlarge"
        required: true
      - name: "Disk size"
        unit: Go
        description: "Disk size for the Nexus Repository."
        key: vm_disk_size
        widget: slider_range
        type: integer
        default: 20
        values:
            - 20
            - 250
        required: true
    - name: SSH Keypair for new instances
      technologies: [pipeline]
      vars:
      - name: "SSH Public key"
        description: "The public SSH key to connect via SSH to execute the Ansible playbook"
        key: keypair_public
        widget: cy_cred
        type: string
        default: "((keypair.ssh_pub))"
        required: true
      - name: "SSH Private key"
        description: "The private SSH key to connect via SSH to execute the Ansible playbook"
        key: keypair_private
        widget: cy_cred
        type: string
        default: "((keypair.ssh_prv))"
        required: true
    - name: Application Configuration
      technologies: [terraform]
      vars:
      - name: "Port"
        description: "Port where Nexus Repository service is exposed."
        key: nexus_port
        widget: simple_text
        type: string
        default: "8081"
        required: true
      - name: "Admin password"
        description: "Initial admin password for Nexus Repository first installation."
        key: nexus_admin_password
        widget: simple_text
        type: string
        default: "changeme"
        required: true

  - name: AWS Cloud Provider
    groups:
    - name: Access Configuration
      technologies: [pipeline]
      vars:
      - name: "AWS account"
        description: "The AWS account where to deploy the infrastructure. It contains access key and secret key."
        key: aws_cred
        widget: cy_cred
        widget_config:
          display_keys: false
          cred_types:
            - aws
        type: string
        default: "((aws))"
      - name: "Amazon AWS region"
        description: "Amazon AWS region to use for Terraform."
        key: aws_region
        widget: auto_complete
        type: string
        values: ["eu-north-1","ap-south-1","eu-west-3","eu-west-2","eu-west-1","ap-northeast-2","ap-northeast-1","sa-east-1","ca-central-1","ap-southeast-1","ap-southeast-2","eu-central-1","us-east-1","us-east-2","us-west-1","us-west-2"]
        default: eu-west-1
        required: true


- name: azure
  sections:
  - name: Nexus Repository
    groups:
    - name: Virtual machine specifications
      technologies: [terraform]
      vars:
      - name: "Instance type"
        description: "Instance type for the Nexus Repository."
        key: vm_instance_type
        widget: slider_list
        type: string
        default: "Standard_DS2_v2"
        values:
            - "Standard_DS1_v2"
            - "Standard_DS2_v2"
            - "Standard_DS3_v2"
        required: true
      - name: "Disk size"
        unit: Go
        description: "Disk size for the Nexus Repository."
        key: vm_disk_size
        widget: slider_range
        type: integer
        default: 30
        values:
            - 30
            - 250
        required: true
    - name: Instance Operations
      technologies: [pipeline]
      vars:
      - name: "Instance status"
        description: "Instance status for the Nexus Repository."
        key: vm_instance_status
        widget: dropdown
        type: string
        default: "Running"
        values:
            - "Running"
            - "Stopped"
        required: true
    - name: SSH Keypair for new instances
      technologies: [pipeline]
      vars:
      - name: "SSH Public key"
        description: "The public SSH key to connect via SSH to execute the Ansible playbook"
        key: keypair_public
        widget: cy_cred
        type: string
        default: "((keypair.ssh_pub))"
        required: true
      - name: "SSH Private key"
        description: "The private SSH key to connect via SSH to execute the Ansible playbook"
        key: keypair_private
        widget: cy_cred
        type: string
        default: "((keypair.ssh_prv))"
        required: true
    - name: Application Configuration
      technologies: [terraform]
      vars:
      - name: "Port"
        description: "Port where Nexus Repository service is exposed."
        key: nexus_port
        widget: simple_text
        type: string
        default: "8081"
        required: true
      - name: "Admin password"
        description: "Initial admin password for Nexus Repository first installation."
        key: nexus_admin_password
        widget: simple_text
        type: string
        default: "changeme"
        required: true

  - name: Azure Cloud Provider
    groups:
    - name: Access Configuration
      technologies: [pipeline]
      vars:
      - name: "Azure credentials"
        description: "The azure credential used to deploy the infrastructure. It contains subscription_id, tenant_id, client_id, and client_secret."
        key: azure_cred
        widget: cy_cred
        widget_config:
          display_keys: false
          cred_types:
            - azure
        type: string
        default: "((azure))"
        required: true
      - name: "Azure location"
        description: "Azure location for Terraform."
        key: azure_location
        widget: auto_complete
        type: string
        values:
            - Australia Central
            - China East
            - China North
            - East Asia
            - East US
            - France Central
            - France South
            - North Europe
            - Southeast Asia
            - South Africa North
            - South Africa West
            - West Europe
            - West US
        default: "West Europe"
        required: true
    - name: Azure Infrastructure
      technologies: [terraform]
      vars:
      - name: "Resource group name"
        description: "The name of the existing resource group where the resources will be deployed."
        key: rg_name
        widget: simple_text
        type: string
        default: ""
        required: true


- name: gcp
  sections:
  - name: Nexus Repository
    groups:
    - name: Virtual machine specifications
      technologies: [terraform]
      vars:
      - name: "Machine type"
        description: "Machine type for the Nexus Repository."
        key: vm_machine_type
        widget: slider_list
        type: string
        default: "n2-standard-2"
        values:
            - n1-standard-2
            - n2-standard-2
            - n2d-standard-2
        required: true
      - name: "Disk size"
        unit: Go
        description: "Disk size for the Nexus Repository."
        key: vm_disk_size
        widget: slider_range
        type: integer
        default: 20
        values:
            - 10
            - 250
        required: true
    - name: SSH Keypair for new instances
      technologies: [pipeline]
      vars:
      - name: "SSH Public key"
        description: "The public SSH key to connect via SSH to execute the Ansible playbook"
        key: keypair_public
        widget: cy_cred
        type: string
        default: "((keypair.ssh_pub))"
        required: true
      - name: "SSH Private key"
        description: "The private SSH key to connect via SSH to execute the Ansible playbook"
        key: keypair_private
        widget: cy_cred
        type: string
        default: "((keypair.ssh_prv))"
        required: true
    - name: Application Configuration
      technologies: [terraform]
      vars:
      - name: "Port"
        description: "Port where Nexus Repository service is exposed."
        key: nexus_port
        widget: simple_text
        type: string
        default: "8081"
        required: true
      - name: "Admin password"
        description: "Initial admin password for Nexus Repository first installation."
        key: nexus_admin_password
        widget: simple_text
        type: string
        default: "changeme"
        required: true

  - name: GCP Cloud Provider
    groups:
    - name: Access Configuration
      technologies: [pipeline]
      vars:
      - name: "GCP project"
        description: "Google Cloud Platform project ID for Terraform."
        key: gcp_project
        widget: simple_text
        type: string
        default: ""
        required: true
      - name: "GCP region"
        description: "Google Cloud Platform region to use for Terraform."
        key: gcp_region
        widget: auto_complete
        type: string
        default: "europe-west1"
        values:
            - europe-west1
            - europe-west2
            - europe-west3
            - europe-north1
            - europe-north2
            - northamerica-northeast1
            - northamerica-northeast2
        required: true
      - name: "GCP zone"
        description: "Google Cloud Platform zone to use for Terraform. Make sure the zone extension exists for the selected region."
        key: gcp_zone
        widget: dropdown
        type: string
        default: "b"
        values:
            - a
            - b
            - c
            - d
            - e
            - f
        required: true      
      - name: "GCP credentials"
        description: "Google Cloud Platform JSON credentials to use for Terraform."
        key: gcp_credentials_json
        widget: cy_cred
        type: string
        default: "((gcp.json_key))"
        required: true