---
# Configuration of the Cycloid stack
version: '3'
name: GCP Virtual Machine
canonical: stack-compute-gcp
status: private
author: Cycloid
description: |
  Deploys a GCP Virtual Machine using Terraform.
image: |
  https://cycloid-demo-stacks-logo.s3.eu-west-1.amazonaws.com/gcp-vm.png
keywords:
  - virtual machine
  - instance
  - provider:gcp
technologies:
- technology: terraform
  version: 1.8.3

config:
  inventory:
    name: 'Select resources using Cycloid Asset Inventory.'
    description: 'A VPC is required to be present in the Cycloid Asset Inventory beforehand. You can use the GCP VPC Network to provision these resources.'
    cloud_provider: gcp
    # Pipeline and variable configuration for the default CD pipeline use case
    pipeline:
      pipeline:
        path: pipeline/pipeline.yaml
      variables:
        path: pipeline/variables.sample.yaml
        destination: ($ .project $)/pipeline/($ .environment $)/variables.yaml
    # Configuration of terraform (leave .sample extension to prevent terraform executing the sample file)
    terraform:
      main:
        path: 'terraform/main.tf'
        destination: '($ .project $)/terraform/($ .environment $)/main.tf'

  manual:
    name: 'Enter resource IDs manually in a text field.'
    description: 'A VPC name will need to be entered manually in a text field.'
    cloud_provider: gcp
    # Pipeline and variable configuration for the default CD pipeline use case
    pipeline:
      pipeline:
        path: pipeline/pipeline.yaml
      variables:
        path: pipeline/variables.sample.yaml
        destination: ($ .project $)/pipeline/($ .environment $)/variables.yaml
    # Configuration of terraform (leave .sample extension to prevent terraform executing the sample file)
    terraform:
      main:
        path: 'terraform/main.tf'
        destination: '($ .project $)/terraform/($ .environment $)/main.tf'
