---
# Configuration of the Cycloid stack
version: '2'
name: 'AWS Network Landing Zone'
canonical: stack-network-aws
status: public
author: Cycloid
description: |
  Deploys a VPC with a public and a private subnets in a single AZ, as well as a bastion EC2 instance.
image: |
  https://cycloid-demo-stacks-logo.s3.eu-west-1.amazonaws.com/network.svg
keywords:
- terraform
- network
- vpc
- subnet
- bastion
technologies:
- technology: terraform
  version: 1.5.7

config:
  default:
    name: 'Default'
    description: 'Deploys a VPC, public and private subnets and a bastion'
    cloud_provider: aws
    # Pipeline and variable configuration for the default CD pipeline use case
    pipeline:
      pipeline:
        path: pipeline/pipeline.yaml
      variables:
        path: pipeline/variables.sample.yaml
        destination: ($ project $)/pipeline/($ environment $)/variables.yaml
    # Configuration of terraform (leave .sample extension to prevent terraform executing the sample file)
    terraform:
      main:
        path: 'terraform/main.tf'
        destination: '($ project $)/terraform/($ environment $)/main.tf'
