---
# Configuration of the Cycloid stack
version: '4'
name: 'Test hidden fields'
canonical: test-hidden-fields
author: Cycloid
description: |
  Test hidden fields.
image: |
  https://cycloid-demo-stacks-logo.s3.eu-west-1.amazonaws.com/aws-ec2.svg
keywords:
  - ec2
  - virtual machine
  - instance
  - provider:aws
technologies:
- technology: terraform
  version: 1.8.3

config:
  default:
    pipeline:
      pipeline:
        path: pipeline/pipeline.yml
      variables:
        path: pipeline/variables.sample.yml
        destination: '($ .org $)/($ .project $)/($ .env $)/($ .component $)/pipeline/variables.yml'