---
# Configuration of the Cycloid stack
version: '3'
name: Azure Virtual Machine
canonical: stack-compute-azure
status: private
author: Cycloid
description: |
  Deploys an Azure Virtual Machine using Terraform.
image: |
  https://cycloid-demo-stacks-logo.s3.eu-west-1.amazonaws.com/azure-vm.png
keywords:
  - virtual machine
  - instance
  - provider:azure
technologies:
  - technology: n/a

config:
  inventory:
    name: 'Select resources using Cycloid Asset Inventory'
    description: 'A Resource Group is required to be present in the Cycloid Asset Inventory beforehand. You can use the Azure Virtual Network to provision these resources.'
    cloud_provider: azurerm
    # Pipeline and variable configuration for the default CD pipeline use case
    pipeline:
      pipeline:
        path: pipeline/pipeline.yaml
      variables:
        path: pipeline/variables.sample.yaml
        destination: ($ .project $)/pipeline/($ .environment $)/variables.yaml
    # Configuration of terraform (leave .sample extension to prevent terraform executing the sample file)
    terraform:
      main:
        path: 'terraform/main.tf'
        destination: '($ .project $)/terraform/($ .environment $)/main.tf'

  manual:
    name: 'Enter resource names manually in a text field.'
    description: 'A Resource Group name will need to be entered manually in a text field.'
    cloud_provider: azurerm
    # Pipeline and variable configuration for the default CD pipeline use case
    pipeline:
      pipeline:
        path: pipeline/pipeline.yaml
      variables:
        path: pipeline/variables.sample.yaml
        destination: ($ .project $)/pipeline/($ .environment $)/variables.yaml
    # Configuration of terraform (leave .sample extension to prevent terraform executing the sample file)
    terraform:
      main:
        path: 'terraform/main.tf'
        destination: '($ .project $)/terraform/($ .environment $)/main.tf'
