---
version: "2"
use_cases:
- name: aks
  sections:
  - name: Azure Kubernetes Service (AKS)
    groups:
    - name: Azure Cloud Configuration
      technologies: [pipeline]
      vars:
      - name: "Azure Credentials"
        description: "The azure credential used to deploy the infrastructure. It contains subscription_id, tenant_id, client_id, and client_secret."
        key: azure_cred
        widget: cy_cred
        widget_config:
          display_keys: false
          cred_types:
            - azure
        type: string
        default: "((azure))"
        required: true
    - name: Azure Infrastructure
      technologies: [terraform]
      vars:
      - name: "Resource Group Name"
        description: "The name of the existing resource group where the resources will be deployed."
        key: resource_group_name
        widget: cy_inventory_resource
        widget_config:
          attribute: name
          filters:
            type: azurerm_resource_group
        type: string
        required: true
      - name: "Kubernetes Version"
        description: "The Kubernetes version to use."
        key: kubernetes_version
        widget: auto_complete
        type: string
        values:
        - "1.29.2"
        - "1.29.1"
        - "1.28.7"
        - "1.28.6"
        - "1.27.11"
        - "1.27.10"
        default: "1.29.2"
        validations: 
        - regexp: "^1.[0-9]{2}.*$"
          error_message: "Please enter a valid Kubernetes version such as `1.29` or `1.29.2`"
        required: true
      - name: "Kubernetes SKU Tier"
        description: "The SKU Tier that should be used for this Kubernetes Cluster."
        key: kubernetes_sku_tier
        widget: dropdown
        type: string
        values:
        - "Free"
        - "Standard"
        - "Premium"
        default: "Free"
        required: true

- name: nodepool
  sections:
  - name: Azure Kubernetes Service (AKS)
    groups:
    - name: Azure Cloud Configuration
      technologies: [pipeline]
      vars:
      - name: "Azure Credentials"
        description: "The azure credential used to deploy the infrastructure. It contains subscription_id, tenant_id, client_id, and client_secret."
        key: azure_cred
        widget: cy_cred
        widget_config:
          display_keys: false
          cred_types:
            - azure
        type: string
        default: "((azure))"
        required: true
    - name: Azure Infrastructure
      technologies: [terraform]
      vars:
      - name: "Azure Kubernetes cluster (AKS)"
        description: "The existing Azure Kubernetes cluster (AKS) where the nodepool will be deployed."
        key: kubernetes_cluster_id
        widget: cy_inventory_resource
        widget_config:
          attribute: id
          filters:
            type: azurerm_kubernetes_cluster
        type: string
        required: true
      - name: "Node Pool Name"
        description: "The name of the Node Pool."
        key: nodepool_name
        widget: simple_text
        type: string
        default: ""
        validations: 
        - regexp: "^[a-z]{1}[a-z0-9]{0,11}$"
          error_message: "Must begin with a lowercase letter, contain only lowercase letters and numbers and no more than 12 chars in length."
        required: true
      - name: "VM Size"
        description: "The SKU which should be used for the Virtual Machines used in this Node Pool. Changing this forces a new resource to be created."
        key: nodepool_vm_size
        widget: slider_list
        type: string
        default: "Standard_DS2_v2"
        values:
            - "Standard_DS2_v2"
            - "Standard_DS3_v2"
            - "Standard_DS4_v2"
        required: true
      - name: "Number of Nodes"
        unit: Nodes
        description: "The initial number of nodes which should exist within this Node Pool. Valid values are between 0 and 1000 (inclusive) for user pools and between 1 and 1000 (inclusive) for system pools and must be a value in the range min_count - max_count."
        key: nodepool_node_count
        widget: slider_range
        type: integer
        default: 1
        values:
            - 1
            - 4
        required: true
